// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"

	"github.com/mikuto0831/camp2025_vol2/internal/entity"
)

const getUserByUid = `-- name: GetUser :one
SELECT id, uid, user_type_id, name, email, birth, sex, create_at, update_at, delete_at, deleted FROM users
WHERE uid = $1
  AND deleted = false
`

func (q *Queries) GetUserByUid(ctx context.Context, uid string) (entity.User, error) {
	row := q.db.QueryRow(ctx, getUserByUid, uid)
	var i entity.User
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.UserTypeID,
		&i.Name,
		&i.Email,
		&i.Birth,
		&i.Sex,
		&i.CreateAt,
		&i.UpdateAt,
		&i.DeleteAt,
		&i.Deleted,
	)
	return i, err
}
