// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package entity

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Genre struct {
	ID    int32       `json:"id"`
	Hobby pgtype.Int4 `json:"hobby"`
	Name  string      `json:"name"`
}

type Hobby struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type HobbyInstance struct {
	ID          pgtype.UUID      `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	HobbyID     pgtype.Int4      `json:"hobby_id"`
	Title       string           `json:"title"`
	CreatedBy   string           `json:"created_by"`
	ContentsUrl pgtype.Text      `json:"contents_url"`
	ImageUrl    pgtype.Text      `json:"image_url"`
	Geom        interface{}      `json:"geom"`
	CreateAt    pgtype.Timestamp `json:"create_at"`
}

type HobbyMapGenre struct {
	ID              int32       `json:"id"`
	HobbyInstanceID pgtype.UUID `json:"hobby_instance_id"`
	GenreID         pgtype.Int4 `json:"genre_id"`
}

type User struct {
	ID         pgtype.UUID      `json:"id"`
	Uid        string           `json:"uid"`
	UserTypeID pgtype.UUID      `json:"user_type_id"`
	Name       string           `json:"name"`
	Email      string           `json:"email"`
	Birth      pgtype.Date      `json:"birth"`
	Sex        int32            `json:"sex"`
	CreateAt   pgtype.Timestamp `json:"create_at"`
	UpdateAt   pgtype.Timestamp `json:"update_at"`
	DeleteAt   pgtype.Timestamp `json:"delete_at"`
	Deleted    pgtype.Bool      `json:"deleted"`
}

type UserType struct {
	ID   pgtype.UUID `json:"id"`
	Type string      `json:"type"`
}
